/**
 * src/app/api/cloudinary/sign/route.ts
 *
 * API Route — Cloudinary Signed Upload
 *
 * Clients call POST /api/cloudinary/sign with a JSON body specifying the
 * upload preset.  This handler:
 *  1. Verifies the user is authenticated.
 *  2. Validates that the caller has sufficient role for the requested preset.
 *  3. Returns a signed upload payload generated by the server-side Cloudinary SDK.
 *
 * The client then uses the signature to upload directly to Cloudinary
 * without the api_secret ever leaving the server.
 */

import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";
import { signUploadRequest, type UploadPreset } from "@/src/lib/cloudinary";
import type { UserRole } from "@/types/database";

// ─── Role → allowed presets map ───────────────────────────────────────────────

/**
 * Defines which upload presets each role may access.
 * If a role is not listed its allowed presets default to avatar only.
 */
const PRESET_ROLE_REQUIREMENTS: Record<UploadPreset, UserRole[]> = {
  // Any authenticated user may update their own avatar
  avatar: [
    "Public User", "SAAHS Member", "Executive Body Member",
    "Governing Body Member", "Literary Secretary", "Treasurer",
    "General Secretary", "Vice President", "President",
  ],
  // Event banners: admins + literary secretary
  event_banner: ["Literary Secretary", "General Secretary", "Vice President", "President"],
  // Notice attachments: same as event banner
  notice_attachment: ["Literary Secretary", "General Secretary", "Vice President", "President"],
  // Library resources: literary secretary and above
  library_resource: ["Literary Secretary", "General Secretary", "Vice President", "President"],
  // Grievance attachments: any authenticated user
  grievance_attachment: [
    "Public User", "SAAHS Member", "Executive Body Member",
    "Governing Body Member", "Literary Secretary", "Treasurer",
    "General Secretary", "Vice President", "President",
  ],
  // Meeting attachments: admin core only
  meeting_attachment: ["General Secretary", "Vice President", "President"],
};

// ─── Route Handler ────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    // 1. Parse request body
    const body = await request.json().catch(() => null);

    if (!body || typeof body.preset !== "string") {
      return NextResponse.json(
        { error: "Request body must include a valid `preset` string." },
        { status: 400 }
      );
    }

    const preset = body.preset as UploadPreset;
    const publicId: string | undefined = typeof body.public_id === "string"
      ? body.public_id
      : undefined;

    // Validate preset name
    if (!Object.keys(PRESET_ROLE_REQUIREMENTS).includes(preset)) {
      return NextResponse.json(
        { error: `Unknown preset "${preset}".` },
        { status: 400 }
      );
    }

    // 2. Authenticate
    const supabase = await createSupabaseServerClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: "Authentication required." },
        { status: 401 }
      );
    }

    // 3. Authorise: check the caller's role against the preset requirement
    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();

    if (!profile) {
      return NextResponse.json(
        { error: "Profile not found." },
        { status: 403 }
      );
    }

    const allowedRoles = PRESET_ROLE_REQUIREMENTS[preset];
    if (!allowedRoles.includes(profile.role as UserRole)) {
      return NextResponse.json(
        {
          error: `Your role ("${profile.role}") is not permitted to upload "${preset}" assets.`,
        },
        { status: 403 }
      );
    }

    // 4. For avatar uploads, force the public_id to include the user's own UUID
    //    so users cannot overwrite other users' avatars.
    const resolvedPublicId =
      preset === "avatar" ? `saahs/avatars/${user.id}` : publicId;

    // 5. Generate the signed payload
    const signature = await signUploadRequest(preset, resolvedPublicId);

    return NextResponse.json(signature, { status: 200 });
  } catch (err) {
    console.error("[api/cloudinary/sign] Unexpected error:", err);
    return NextResponse.json(
      { error: "Internal server error generating upload signature." },
      { status: 500 }
    );
  }
}
