-- =============================================================================
-- SAAHS — Migration 002: Custom Google Auth + Institutions
-- Description:
--   1. Detaches `profiles` from Supabase Auth (`auth.users`) so a hand-rolled
--      Google OAuth flow can own user identity instead of Supabase Auth.
--   2. Adds an admin-managed `institutions` table plus `institution` and
--      `id_card_url` columns on `profiles` for the onboarding form.
--
-- Note on RLS: existing policies that key off `auth.uid()` are left in place
-- but are no longer reachable in practice — the app now talks to Postgres
-- exclusively through the service-role key (which bypasses RLS) and enforces
-- authorization in application code, matching the pattern already used
-- throughout app/actions/**. They're harmless to leave and cheap to revisit
-- later if an anon/authenticated-key client is reintroduced for these tables.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SECTION 1: Detach profiles from Supabase Auth
-- ---------------------------------------------------------------------------

-- Profile creation now happens in our own /auth/callback route, not a trigger
-- on auth.users (we no longer write to auth.users at all).
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_auth_user();

-- profiles.id is now just a plain UUID primary key (generated by the app at
-- sign-up time), no longer required to reference an auth.users row.
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- Stable Google account identifier ("sub" claim from the verified ID token).
-- This is how returning users are matched back to their profile row.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS google_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_google_id ON public.profiles (google_id);

-- ---------------------------------------------------------------------------
-- SECTION 2: Institutions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.institutions (
  id         BIGSERIAL   PRIMARY KEY,
  name       TEXT        NOT NULL UNIQUE,
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.institutions IS 'Admin-managed list of institutions offered on the onboarding form.';

INSERT INTO public.institutions (name) VALUES ('PGIMER')
  ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- SECTION 3: Profile fields for onboarding
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS institution TEXT DEFAULT 'PGIMER';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS id_card_url TEXT;

COMMENT ON COLUMN public.profiles.institution  IS 'Selected from the admin-managed institutions table; defaults to PGIMER.';
COMMENT ON COLUMN public.profiles.id_card_url  IS 'MinIO delivery URL for the uploaded student/staff ID card image.';

-- =============================================================================
-- END OF MIGRATION: 002_custom_auth_and_institutions.sql
-- =============================================================================
